name: dealermotor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter: 
    sdk: flutter
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1

dev_dependencies: 
  flutter_lints: ^6.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/

